# Generated by Django 5.0.3 on 2024-03-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('prename', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=2)),
            ],
        ),
    ]
